'use client';
import { createContext, useContext, useEffect, useState } from 'react';
import { onAuthStateChanged, signOut, User } from 'firebase/auth';
import { doc, getDoc, collection, getDocs, setDoc } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

interface AuthContextType {
    user: User | null;
    role: 'super_admin' | 'salon_admin' | 'user' | null;
    salonId: string | null;
    loading: boolean;
    logout: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType>({ user: null, role: null, salonId: null, loading: true, logout: async () => { } });

export const AuthProvider = ({ children }: { children: React.ReactNode }) => {
    const [user, setUser] = useState<User | null>(null);
    const [role, setRole] = useState<'super_admin' | 'salon_admin' | 'user' | null>(null);
    const [salonId, setSalonId] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, async (authUser) => {
            if (authUser) {
                setUser(authUser);

                // PERFORMANCE OPTIMIZATION: Super Admin ise DB bekleme
                const knownSuperAdmins = ['error_3@hotmail.com', 'ilhamiilhan55@gmail.com'];
                const userEmail = authUser.email ? authUser.email.toLowerCase() : '';

                if (knownSuperAdmins.includes(userEmail)) {
                    console.log("⚡ Hızlı Giriş: Super Admin");
                    setRole('super_admin');
                    setSalonId(null);
                    setLoading(false); // Hemen loading bitir

                    // Arka planda DB kaydı var mı kontrol et (yoksa oluştur)
                    try {
                        const userDoc = await getDoc(doc(db, 'users', authUser.uid));
                        if (!userDoc.exists()) {
                            await setDoc(doc(db, 'users', authUser.uid), {
                                email: userEmail,
                                role: 'super_admin',
                                createdAt: new Date().toISOString(),
                                note: 'Auto-generated by AuthContext (VIP Fast Path)'
                            });
                            console.log("✅ Super Admin DB Kaydı Oluşturuldu");
                        }
                    } catch (e) {
                        console.error("Arka plan DB kontrol hatası:", e);
                    }
                    return; // Fonksiyondan çık
                }

                // Normal kullanıcılar için DB sorgusu
                try {
                    const userDoc = await getDoc(doc(db, 'users', authUser.uid));
                    if (userDoc.exists()) {
                        const userData = userDoc.data();
                        setRole(userData.role);

                        if (userData.salonId) {
                            setSalonId(userData.salonId);
                        } else {
                            const salonsSnapshot = await getDocs(collection(db, 'salons'));
                            const foundSalon = salonsSnapshot.docs.find(doc => {
                                const data = doc.data();
                                return data.admins && Array.isArray(data.admins) && data.admins.some((admin: any) =>
                                    (typeof admin === 'string' && admin === authUser.email) ||
                                    (typeof admin === 'object' && admin.email === authUser.email)
                                );
                            });

                            if (foundSalon) {
                                setSalonId(foundSalon.id);
                            } else {
                                setSalonId(null);
                            }
                        }
                    } else {
                        setRole('user');
                        setSalonId(null);
                    }
                } catch (error) {
                    console.error("Rol/Salon çekme hatası:", error);
                    setRole('user');
                    setSalonId(null);
                }
            } else {
                setUser(null);
                setRole(null);
                setSalonId(null);
            }
            setLoading(false);
        });
        return () => unsubscribe();
    }, []);

    const logout = async () => {
        await signOut(auth);
        setUser(null);
        setRole(null);
        setSalonId(null);
    };

    return (
        <AuthContext.Provider value={{ user, role, salonId, loading, logout }}>
            {children}
        </AuthContext.Provider>
    );
};

export const useAuth = () => useContext(AuthContext);
